version: "3"

services:
#  frontend:
#    container_name: app_frontend 
#    build: ./frontend
#    ports:
#      - 3000:3000
#    platform: linux/x86_64
#    working_dir: /frontend
#    depends_on:
#      - backend
#  backend:
#    container_name: app_backend
#    build: ./backend
#    ports:
#      - 3001:3001
#    platform: linux/x86_64
#    working_dir: /backend
#    depends_on:
#      - db
#    environment:
#      - APP_PORT=3001
#      - JWT_SECRET=jwt_secret
#      - DB_USER=postgres
#      - DB_PASS=123456
#      - DB_HOST=db
#      - DB_PORT=5432
  db:
    image: postgres
    container_name: diary_of_emotions_db
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=dbps
    restart: always
